apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-express
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8-express
  template:
    metadata:
      labels:
        app: k8-express
    spec:
      containers:
      - name: k8-express
        image: n61n3/k8-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3030
