apiVersion: v1
kind: Service
metadata:
  name: k8-express-nginx
spec:
  type: LoadBalancer
  selector:
    app: k8-express-nginx
  ports:
  - port: 3333
    targetPort: 3030

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-express-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-express-nginx
  template:
    metadata:
      labels:
        app: k8-express-nginx
    spec:
      containers:
      - name: k8-express-nginx
        image: n61n3/k8-express-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3030
